version: '3'
services:
  zookeeper:
    image: "bitnami/zookeeper"
    container_name: zookeeper
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  kafka:
    image: "bitnami/kafka"
    container_name: kafka
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
  egeria:
    image: "odpi/egeria"
    container_name: egeria
    ports:
      - "9443:9443"
  egeria-react-ui:
    # build: .
    container_name: egeria-react-ui
    image: "egeria-cra-client:1.0.1"
    environment: 
      - EGERIA_PRESENTATIONSERVER_SERVER_aaa={"remoteServerName":"cocoView1","remoteURL":"https://egeria:9443"}
      - NODE_ENV=production
    ports:
      - "8091:8091"
networks:
  default:
    external:
      name: egeria-network